server:
  port: 8074

spring:

  thymeleaf:
    cache: false

  mail:
    host: smtp.qq.com
    password: jitpobbejmhjdhgg    # 邮箱授权码
    username: 2684270465@qq.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  rabbitmq:
    username: guest
    password: guest
    host: 192.168.108.128
    port: 5672

eureka:
  client:
    service-url:
      defaultZone: http://192.168.108.127:8082/eureka
    registry-fetch-interval-seconds: 5

amqp:
  email:
    exchange: amqp.email # 交换机名称
    emailQueue: email.queue # 队列名称
    emailKey: email.key